### ISSUE TITLE
Filler Text on Managed Properties.

### ISSUE THREAD

**Issue by Smokey-Dev** [Project-Sloth/ps-realtor#10]
![image](https://github.com/Project-Sloth/ps-realtor/assets/86137349/ceaba21b-20e6-454b-b1b7-1a69086b2fde)
 
Very small (Not even an issue honestly) When managing a already made property. The filler is not set. Still shows the Lorem lpsum. I am sure this was just left until figured out what is suppose to get put there.

**Comment by LeSiiN** [comment]
https://github.com/Project-Sloth/ps-realtor/pull/1 - already in this PR
