### ISSUE TITLE
Cant create house

### ISSUE THREAD

**Issue by gg1010** [Project-Sloth/ps-realtor#11]
I cant create any houses its just frezes
![image](https://github.com/Project-Sloth/ps-realtor/assets/55393468/5aa87b54-6b75-4345-98b2-c1a0729e4d42)
![image](https://github.com/Project-Sloth/ps-realtor/assets/55393468/4234f2aa-693c-43e6-b84d-869ec7fff7ca)

**Comment by gg1010** [comment]
Can be IDK its my friend that has been working on it and he cant remember his login to github

**Comment by gg1010** [comment]
I can try and download a new version and use that and se if that works

**Comment by gg1010** [comment]
Fresh install
![image](https://github.com/Project-Sloth/ps-realtor/assets/55393468/f66ba755-85f5-4372-9ba9-117708f03f00)

**Comment by DPrpDev** [comment]
I get this same error even with latest update

**Comment by DPrpDev** [comment]
> I cant create any houses its just frezes ![image](https://user-images.githubusercontent.com/55393468/260047852-5aa87b54-6b75-4345-98b2-c1a0729e4d42.png) ![image](https://user-images.githubusercontent.com/55393468/260048453-4234f2aa-693c-43e6-b84d-869ec7fff7ca.png)

having you installed ps-housing?

**Comment by gg1010** [comment]
> > I cant create any houses its just frezes ![image](https://user-images.githubusercontent.com/55393468/260047852-5aa87b54-6b75-4345-98b2-c1a0729e4d42.png) ![image](https://user-images.githubusercontent.com/55393468/260048453-4234f2aa-693c-43e6-b84d-869ec7fff7ca.png)
> 
> having you installed ps-housing?

Yes
