### ISSUE TITLE
Tablet stuck in hand

### ISSUE THREAD

**Issue by HighlineUK** [Project-Sloth/ps-realtor#13]
Hi. the tablet seems to get stuck in the hand. 
![image](https://github.com/Project-Sloth/ps-realtor/assets/23699443/3ad1ebd7-2b0a-44cc-a977-8a2e2886ce21)

**Comment by HighlineUK** [comment]
Update: this seems to only happen when you enter the property after 'Showcase' is selected and you enter the building. When you leave it does disappear.

**Comment by LeSiiN** [comment]
how do u even do this? u cant walk when inside the realtor?

**Comment by LeSiiN** [comment]
cant be replicated

**Comment by HighlineUK** [comment]
ok...if you edit the building details (change from Apartment  unfurnished to apartment furnish for example) whilst in the property (you'll pull the tablet out), you'll end up outside. when you them showcase the new apartment, the tablet appears.

**Comment by HighlineUK** [comment]
https://drive.google.com/file/d/15uSIGgHQUqSriUjxyge0i3kBnKj6A-cQ/view?usp=sharing

**Comment by LeSiiN** [comment]
I dont know how i should fix this issue

**Comment by HighlineUK** [comment]
Would live to assist but it only appears if you edit a property shell, whilst in the shell...which you shouldn't do anyway. Plus the tablet disappears when you go outside anyway. Its a low issue bug.
