### ISSUE TITLE
New house

### ISSUE THREAD

**Issue by gg1010** [Project-Sloth/ps-realtor#17]
When i am trying to make a new house its just frezes and i can't close it.
![image](https://github.com/Project-Sloth/ps-realtor/assets/55393468/2e55eb78-c1b3-4c33-8afd-79225a085adf)

**Comment by MonkeyWhisper** [comment]
Your issue. Stop reposting this or you'll be back from interacting with our GitHub repos.
https://gyazo.com/21b1ad20c15d9bd00f02d5c6ab9a3c59
