### ISSUE TITLE
Some UI issues

### ISSUE THREAD

**Issue by jellyton69** [Project-Sloth/ps-realtor#2]
Running on a 2K monitor

Badges run off of the card:
![FiveM_b2699_GTAProcess - August11 - 02 55 - 2648](https://github.com/Project-Sloth/ps-realtor/assets/20498875/04bb546c-b6b6-4eec-91de-e3142bda951c)

The properties grid does not utilize the full height of the page, leaving a lot of blank space:
![FiveM_b2699_GTAProcess - August11 - 02 56 - 2649](https://github.com/Project-Sloth/ps-realtor/assets/20498875/26784454-2e15-45d7-8f57-486263cdd032)

Weird Behavior with View Property Button:
https://github.com/Project-Sloth/ps-realtor/assets/20498875/a91ee347-2c25-4799-a826-f6b071b36fbb

Property Banner is the hero banner on the front page, and you cannot select the gallery images to take a closer look at them.
![FiveM_b2699_GTAProcess - August11 - 02 59 - 2652](https://github.com/Project-Sloth/ps-realtor/assets/20498875/787e9fdf-5b1a-4752-9af1-e2c3271c8e75)

**Comment by LeSiiN** [comment]
Can confirm everything, using 1920x1080

**Comment by MonkeyWhisper** [comment]
Currently it only supports 1920 x 1080, we'll push update for abnormal screeen sizes.
