### ISSUE TITLE
For Sale Issue

### ISSUE THREAD

**Issue by Smokey-Dev** [Project-Sloth/ps-realtor#25]
https://youtu.be/s1mwhPRUNqo

When creating a house. It is put under the "For Sale" 

Manage Property does not show the house "For Sale"

When flipping property over to "For Sale" property does not show that it is for sale anymore.

**Comment by MonkeyWhisper** [comment]
https://github.com/Project-Sloth/ps-realtor/commit/93f26467229a77da3321f1cde4565291c44a8b86
