### ISSUE TITLE
nill value ,,local targetPlayer''

### ISSUE THREAD

**Issue by LeSiiN** [Project-Sloth/ps-realtor#26]
**Describe the bug**
Happens when i try to remove the current owner inside the manage property menu

**To Reproduce**
1. finalise a house
2. manage property
3. remove the citizenid from the owner

**Screenshots**
https://youtu.be/1Bn0yATmAP8

**Comment by maxcapehd** [comment]
https://i.imgur.com/aWCOEEK.png  Can confirmed, steps reproduced, same error

Will also return the same error if inputting a server id that does not currently exist on the server
