### ISSUE TITLE
Help Center (Button Doesn't Work)

### ISSUE THREAD

**Issue by rxnm** [Project-Sloth/ps-realtor#3]
As shown in the image, the button for Help Center doesn't work.

![Screenshot_1](https://github.com/Project-Sloth/ps-realtor/assets/2183651/03a04ce5-dbb3-47d6-b458-f9255c818b7b)

Thanks :)

**Comment by MonkeyWhisper** [comment]
It's never meant to work, send a PR if you want a function for it.
