### ISSUE TITLE
/housing would load the UI and make the screen freeze

### ISSUE THREAD

**Issue by xmidnite** [Project-Sloth/ps-realtor#34]
Error after using command "/housing" or the tablet to open housing menu for realtors

1. use command /housing
2. once the UI has popped out it would be stuck and the screen is frozen
3. head to console and see the error

![image](https://github.com/Project-Sloth/ps-realtor/assets/34018452/5970a572-069b-47df-899c-e3ddd866ec93)

![image](https://github.com/Project-Sloth/ps-realtor/assets/34018452/2f3201a5-f729-4b9a-8082-64e4a150666d)

No changes made or anything on ps-realtor

**Comment by xmidnite** [comment]
any idea what is this error all about?

**Comment by MonkeyWhisper** [comment]
This will be from your end, hence why I closed this

**Comment by xmidnite** [comment]
It was working fine the other day, no changes made on the server, but suddenly this happens. Only thing that was changed, If I remember correctly, is updating the ox_lib. Thanks
