### ISSUE TITLE
Grade 0 Realestate Agent can't do anything

### ISSUE THREAD

**Issue by adweex** [Project-Sloth/ps-realtor#35]
**Describe the bug**
Based on the config values that are shown below, the real intention of the realtor job was:
- Get a newbie to sell houses
- Later on get promoted to do some managing and selling stuff also getting increasingly better comissions.
- After progressing on the job will be promoted and get access to listing new properties.

The problem is that you cannot sell a property without having access to manage property or at least i didn't found a way to do it. A grade 0 realtor should only sell stuff i agree in that, however it can't be done without giving him the management tab.

```lua
Config.RealtorPerms = {
    manageProperty = 1, --minimum grade to manage property | default 1
    changePropertyForSale = 0, --minimum grade to list property | default 0
    sellProperty = 0, --minimum grade to sell property | default 0
    listNewProperty = 2, --minimum grade to list property | default 2
    deleteProperty = 2, --minimum grade to delete property | default 2
    setApartments = 2, --minimum grade to set apartments for players | default 2
}
```

**To Reproduce**
1. List a new property
2. Set yourself to a grade 0 realtor
3. Try to sell a property to yourself or anyone else. (no idea how)

**Expected behavior**
Grade 0 Realtor has access to the manageProperty menu however unable to change prices, garages, doors...etc Only able to sell and if changePropertyForSale is also 0 then able to change that particular value.

**Screenshots** - No way to sell this property as a grade 0
![image](https://github.com/Project-Sloth/ps-realtor/assets/29953690/e23379c4-da27-488b-b579-cca4a5ac5243)

**Comment by UmeeARP** [comment]
This is something I was looking into also and would be great to have it actually working otherwise there is no progression within the company if implemented this way, it would be great if beside the manage property button there was a sell button with the sell options from the current manage property section.
