### ISSUE TITLE
 Suggestion for change

### ISSUE THREAD

**Issue by LucasMoreschi** [Project-Sloth/ps-realtor#36]
**Describe the Suggested**

Separate property types. House with house interiors, Warahoure with warehouse interiors, office with office. And download different types and put them in Config.lua

**Screenshots**
![Captura de tela 2024-01-13 172104](https://github.com/Project-Sloth/ps-realtor/assets/47189740/0d32eeb1-393b-4bfb-a190-bb7e6b6ea8a0)

**Additional context**
Add back doors option

**Comment by LucasMoreschi** [comment]
Add financing option

**Comment by MonkeyWhisper** [comment]
Sure, do it yourself. Open source.
