### ISSUE TITLE
Error While Click on the Apartments section of /housing

### ISSUE THREAD

**Issue by Peasmith** [Project-Sloth/ps-realtor#37]
**Describe the bug**
I have an error that occurs when I like real estate, open the /housing menu and select the Apartments section. I get this error.

**To Reproduce**
1. Go to '/housing menu '
2. Click on 'Apartments Section'
3. See error

**Expected behavior**
I use the latest version of qb inventory, and I think it has something to do with it,

**Screenshots**
[If applicable, add screenshots to help explain your problem.](https://i.gyazo.com/49f0a58b0e6d0f21e1c3ea76ea8a0f8a.png)

**Comment by hscholtz40** [comment]
Did you manage to get a solution? I have the same issue with ps-inventory
