### ISSUE TITLE
Invalid CDN Images

### ISSUE THREAD

**Issue by Geloteee** [Project-Sloth/ps-realtor#45]
**Describe the bug**
cdn images are not found (I can't make a PR because I don't have the images) also please don't upload them to fivemerr because they are going to be deleted

**To Reproduce**
1. Open the housing tablet

**Expected behavior**
The images of the cdn

**Screenshots**
![image](https://github.com/user-attachments/assets/36b34a83-324b-42b1-8706-cce9538f4d14)

**Additional context**
nothing, is very simple

**Comment by Geloteee** [comment]
I just found this, if someone needs help: https://github.com/ItzMuri/ps-housing-image/

**Comment by MonkeyWhisper** [comment]
> **Describe the bug** cdn images are not found (I can't make a PR because I don't have the images) also please don't upload them to fivemerr because they are going to be deleted
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Open the housing tablet
> 
> **Expected behavior** The images of the cdn
> 
> **Screenshots** ![image](https://private-user-images.githubusercontent.com/92045454/363448551-36b34a83-324b-42b1-8706-cce9538f4d14.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUxNjcwNDcsIm5iZiI6MTcyNTE2Njc0NywicGF0aCI6Ii85MjA0NTQ1NC8zNjM0NDg1NTEtMzZiMzRhODMtMzI0Yi00MmIxLTg3MDYtY2NlOTUzOGY0ZDE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAxVDA0NTkwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ0ZmFkYTQ4ZDc1NWIyY2JhNDljOGVhODVmYmJlY2EwYmM0NmE3YzA2NTczZmNmN2RhZTBmMDEyZjY1OThhMGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OeVx0SQ_-t7DBSY2hbEWTG_jIn5XN3TQIfrk75mqjW4)
> 
> **Additional context** nothing, is very simple

You are wrong. Uploading to Fivemerr does not delete images. 

Send a PR if you want to update the images.

**Comment by Geloteee** [comment]
I meant that if the account is inactive 60 days, the account is going to be deleted

**Comment by MonkeyWhisper** [comment]
No, only if you have not uploaded any images.

**Comment by Geloteee** [comment]
Oh ok I didnt knew that, thx for the info, also regarding to ps-housing, do you have the images from all the houses so I can upload them to fivemerr? In the repo that I sended before some images are missing
