### ISSUE TITLE
Set Waypoint (Button Doesn't Work)

### ISSUE THREAD

**Issue by rxnm** [Project-Sloth/ps-realtor#5]
As shown in the image, the button for the (Set Waypoint) doesn't work.

![Screenshot_3](https://github.com/Project-Sloth/ps-realtor/assets/2183651/276a81f9-ce7c-4567-ad94-0738f0e4ce07)

Thanks :)

**Comment by MonkeyWhisper** [comment]
https://github.com/Project-Sloth/ps-realtor/pull/14
