### ISSUE TITLE
UpdateGarage, UpdateDoor not working

### ISSUE THREAD

**Issue by ajay2188** [Project-Sloth/ps-realtor#55]
**Describe the bug**  
When attempting to update a property with either a "door" or "garage" type, the server-side event `bl-realtor:server:updateProperty` throws an error indicating a `nil value for H`. This occurs because the heading (`H`) value is not included in the `newData` object, which only contains the X, Y, and Z coordinates.

**To Reproduce**  
1. Open the UI to start zone placement.  
2. Select the type as either "door" or "garage".  
3. Confirm placement using the UI.  
4. Observe the error in the server logs indicating a missing `H` value.

**Expected behavior**  
The `newData` object should include the heading (`H`) value along with the X, Y, and Z coordinates. The server event should process the data without errors.

**Screenshots**  
If applicable, include any screenshots of the error logs or in-game messages showing the issue.

**Additional context**  
- The issue arises from `GetEntityCoords(ped)` returning only X, Y, and Z coordinates, and the heading (`H`) is not explicitly added to `newData`.  
- The fix involves creating a structured table for `newData` that includes the heading (`H`) by using `MathFloor(GetEntityHeading(ped))`.  

---

### Fixed Code Explanation  
In the fixed code:  
- `newData` is restructured into a table that explicitly includes `x`, `y`, `z`, and `h` values.  
- This ensures that the `H` value is correctly included in both the `garage` and `door` data sent to the server.  
- The UI message for `garageMade` now also includes the `H` value, fixing any related client-side inconsistencies.
![Code_gAhy7ljVzl](https://github.com/user-attachments/assets/dd1491e9-5630-404a-9829-44d230ff97e8)

**Comment by MonkeyWhisper** [comment]
Hi, thanks for this. If you can send a PR for credit, I'd appreciate it. If not, I'll PR it myself, thanks!

**Comment by ajay2188** [comment]
sure, i will create PR in 15-20min
