### ISSUE TITLE
Manage Shells Scroller Non Existent?!

### ISSUE THREAD

**Issue by rxnm** [Project-Sloth/ps-realtor#6]
Not sure if it is meant to even have one, but it really does not show very well with the dark theme that there are more than 4 shells to choose from as shown in the image. Maybe a light-colored scroller would make it better? (this is maybe a suggestion rather than a bug).

![Screenshot_4](https://github.com/Project-Sloth/ps-realtor/assets/2183651/5435a45c-937c-4d95-9dc1-777b25263f6e)

Thanks :)

**Comment by MonkeyWhisper** [comment]
Send a PR if you want it.
