### ISSUE TITLE
Thumnails Do Not Enlarge

### ISSUE THREAD

**Issue by rxnm** [Project-Sloth/ps-realtor#7]
As shown in the image, the thumbnails of the images of a house/apartment do not expand as intended?! (maybe this is not a bug, more of a suggestion)

![Screenshot_5](https://github.com/Project-Sloth/ps-realtor/assets/2183651/4ac37597-8d3f-4201-bf62-8ddad04bd1d7)

Thanks :)

**Comment by MonkeyWhisper** [comment]
They're never meant to expand. Send a PR if you want it.
