### ISSUE TITLE
Global Tenants ( apartment tab )

### ISSUE THREAD

**Issue by LeSiiN** [Project-Sloth/ps-realtor#9]
![Ska6779](https://github.com/Project-Sloth/ps-realtor/assets/103898231/f91f8fad-554d-42a6-a263-738beac101cb)
Global tenants should show how much people out of every character out there is in this apartment

**Comment by MonkeyWhisper** [comment]
Fixed

![image](https://github.com/Project-Sloth/ps-realtor/assets/82112471/4eb8ff9d-cffb-4f3d-b678-748956ed6499)
